Multi section resources
lightsprint09/DBNetworkStack-Sourcing pull request #18
Opened 2017-10-12 13:04 UTC by lightsprint09

Support for Resource with two dimensional array result

2017-10-18 19:57 UTC, dennispost requested changes
Please check all your code and comments for 'contents' as there is no plural of content. ;-) http://dictionary.cambridge.org/de/grammatik/britisch-grammatik/content-or-contents

2017-10-18 19:57 UTC, dennispost commented on DBNetworkStack+Sourcing/ResourceDataProvider.swift
>      /// Describes the current stae of the data provider. Listen for state changes with the `whenStateChanges` callback
Typo: [...] current state of [...]

2017-10-18 19:57 UTC, dennispost commented on DBNetworkStack+Sourcing/ResourceDataProvider.swift
> +     Creates an instance which fetches a gives resource and exposes the result as a DataProvider.
Typo: [...] wich fetches a given resource [...]

2017-10-18 19:57 UTC, dennispost commented on DBNetworkStack+Sourcing/ResourceDataProvider.swift
> +     Creates an instance which fetches a gives resource and exposes the result as a DataProvider.
Typo: [...] wich fetches a given resource [...]

2017-10-18 19:57 UTC, dennispost commented on DBNetworkStack+Sourcing/ResourceDataProvider.swift
> +    private func dataProviderDidChangeContets() {
Typo: dataProviderDidChangeContent

2017-10-18 19:57 UTC, dennispost commented on DBNetworkStack+SourcingTests/RessourceDataProviderTests.swift
>      func testOnNetworkRequestCanceledWithNoEmptyData() {
Same test as in line 154?

2017-10-23 05:57 UTC, ahersch submitted a review, later dismissed

2017-10-26 05:55 UTC, merged